- name:  Install packages ad deploy file on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      apt:
        name:  "{{ item }}"
        state: present 
      loop: 
        - nginx
        - curl
        - git

    - name: Copy file if OS is Ubuntu
      copy:
        src: ./example.txt
        dest: /tmp/example.txt
      when: ansible_facts['distribution'] == "Ubuntu"